[package]
name = "ribeye"
version = "0.0.1"
edition = "2021"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/ribeye"
documentation = "https://docs.rs/ribeye"
description = """
Rust framework for BGP RIB data processing.
"""
keywords = ["bgp", "bgpkit", "api"]

[dependencies]

thiserror = "1.0"
tracing = "0.1"
bgpkit-parser = "0.9.4"
oneio = {version="0.11.0", features = ["lib", "s3"]}

[dev-dependencies]
tracing-subscriber = "0.3.17"